### ISSUE TITLE
Hello your work is much appreciated i wanted to be part of this repository. and i'll be glad if i can contribute the java and javascript solutions thank you.

### ISSUE THREAD

**Issue by saurabhcoded** [getlost01/gfg-potd#11]

**Comment by getlost01** [comment]
Hi, Thanks for reaching me. 

The purpose of this repository is to share my approach to solving the GFG POTD. By doing this I get motivated as it encourages me to solve daily problems and makes me think of the solutions in an optimized manner. I also create editorials for collaboration, inviting others to share their insights.

I want to clarify that I'm against copy-pasting solutions.  Therefore, I provide crisp approaches and corresponding C++ code. If you're passionate about coding and seek guidance, my approach can be a valuable reference. The language in the editorial is for reference only; If the editorial becomes too long, it might indirectly promote copy-pasting, because no one reads the approach they just copy-paste it.

I'm always open to engaging in healthy discussions about different problem-solving approaches. However, **sharing complete solutions in a different language is not the ideal way for me.**

Thanks again,
`<Happy Coding />`

**Comment by saurabhcoded** [comment]
Thank you i'm happy to hear about this.
